# Generated by Django 5.0.4 on 2024-05-15 08:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_alter_categories_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='categories',
            name='slug',
            field=models.SlugField(default=1, editable=False, max_length=30),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='product',
            name='slug',
            field=models.SlugField(default=1, editable=False, max_length=30),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='valyuta',
            name='slug',
            field=models.SlugField(default=1, editable=False, max_length=30),
            preserve_default=False,
        ),
    ]
